# This exposes mongodb inside the cluster
apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis
  name: redis
spec:
  ports:
    - port: 6379 # service available here
      targetPort: 6379 # access this port inside the pod
  selector:
    component: redis