apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: eternal-ws
  name: eternal-ws
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: eternal-ws
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
