# It would be nice to understand apiVersion better. On minikube, I used
# extensions/v1beta1 as per page 264 of kubernetes pdf. In current online docs,
# ReplicaSet is in apps/v1, but this returned a server error on my Minikube
# install. See replica docs here:
# https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#example
#
# $ kubectl api-versions # this command might be helpful
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            # /data/db is the default mongodb path
            mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-storage
