# This is kindof like a service for a persistent volume. It names a volume
# selector. A pod can references the named volume selector, and then that pod's
# spec is portable to any host that includes a persistent volume matching the
# selector.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage
spec:
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      volume: mongo-storage
  accessModes:
    - ReadWriteOnce