apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: eternal-certs
  namespace: charles
spec:
  secretName: eternal-certs
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - xtc.world
  - xct.world
  - x7.world
  - xys.world
  acme:
    config:
    # for http1, you must specify EITHER `ingress-class` OR `ingress`
    - http01:
        # creating this certificate can modify an existing ingress resource.
        # Specify which ingress to modify using the ingress field. 
        # ingress: example-ingress
        ingress-class: nginx
      domains:
      - xtc.world
      - xct.world
      - x7.world
      - xys.world
