apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: eternal-frontend
  name: eternal-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: eternal-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
