apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: eternal-http
  name: eternal-http
  selfLink: /apis/extensions/v1beta1/namespaces/charles/deployments/eternal-http
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: eternal-http
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: eternal-http
    spec:
      containers:
      - image: gcr.io/pixelaether/eternal-http:v0.0.1-rc2
        # command: ['env']
        envFrom:
        - configMapRef:
            name: synk
        env:
        - name: SYNK_MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: synk
              key: pass
        imagePullPolicy: IfNotPresent
        name: eternal-http
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
