apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: eternal-http
  name: eternal-http
  selfLink: /api/v1/namespaces/charles/services/eternal-http
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: eternal-http
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
